global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi_llm"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "gpu"
    metrics_path: /metrics
    static_configs:
      - targets: ["dcgm-exporter:9400"]
